- name: set up variables
  set_fact:
    tar_version: "{{ tar_version | d('1.32-4') }}"
    os: "{{ os | d(default_os) }}"
    osv: "{{ osv | d(default_osv) }}"
    arch: "{{ arch | d(default_arch) }}"
    url_prefix: "http://update.cs2c.com.cn:8080/NS"

- name: set up major and minor
  set_fact:
    major: "{{ osv.split('sp')[0] }}"
    minor: "sp{{ osv.split('sp')[1] }}"
  when: os == 'kylin'

- name: set up cpu for kylin amd64
  set_fact:
    cpu: "x86_64"
  when:
  - os == 'kylin'
  - arch == 'amd64'

- name: set up cpu for kylin arm64
  set_fact:
    cpu: "aarch64"
  when:
  - os == 'kylin'
  - arch == 'arm64'

- name: Install RPM package
  dnf:
    name: "nmap"
    state: present
  when: os == 'kylin'