---
- name: set up variables
  set_fact:
    libssl_version: "{{ libssl_version | d('1.1_1.1.1f-1ubuntu2.23') }}"
    os: "{{ os | d(default_os) }}"
    arch: "{{ arch | d(default_arch) }}"

- name: set up url_prefix for ubuntu amd64
  set_fact:
    url_prefix: "http://archive.ubuntu.com/ubuntu"
  when:
  - os == 'ubuntu'
  - arch == 'amd64'

- name: set up url_prefix for ubuntu arm64
  set_fact:
    url_prefix: "http://ports.ubuntu.com"
  when:
  - os == 'ubuntu'
  - arch == 'arm64'

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: libssl
      pkg_version: "{{ libssl_version }}"
      pkg_feature: "linux-{{ arch }}"
      pkg_fileType: ".deb"
      pkg_url: "{{ url_prefix }}/pool/main/o/openssl/libssl{{ libssl_version }}_{{ arch }}.deb"
  when: os == 'ubuntu'

- name: copy file
  copy:
    src: "{{ downloaded }}"
    dest: "/tmp"
  when: os == 'ubuntu'

- name: install
  apt:
    deb: "/tmp/{{ downloaded | basename }}"
    policy_rc_d: 101
    state: present
  when: os == 'ubuntu'