---
- name: define vars
  set_fact:
    work_dir: "{{ role_path }}/files/tmp/with-upload-module"

- name: prepare tmp compile dir
  file:
    path: "{{ work_dir }}"
    state: directory
  delegate_to: localhost
  run_once: True

- name: compile Caddy with upload module
  vars:
    target_file: "{{ work_dir }}/caddy-{{ caddy_version }}"
  args:
    chdir: "{{ work_dir }}"
    creates: "{{ target_file }}"
  environment:
    GO111MODULE: "on"
    PATH: "{{ role_path }}/files/usr/local/go/bin:{{ lookup('env', 'PATH') }}"
    GOPATH: "{{ role_path }}/files/usr/local/go"
    GOBIN: "{{ role_path }}/files/usr/local/go/bin"
    CADDY_VERSION: "{{ caddy_version }}"
    CADDY_UPLOAD_VERSION: "{{ mod_upload_version }}"
    TARGET_FILE: "{{ target_file }}"
  local_action: command bash {{ role_path }}/files/compile.sh
  run_once: True

- name: install
  copy:
    src: "{{ work_dir }}/caddy-{{ caddy_version }}"
    dest: /opt/caddy/current/caddy
    mode: 755
