---
- name: Node_exporter set var
  set_fact:
    node_exporter_version: 0.18.1

- name: Copy files
  copy:
    src: "{{ role_path }}/files/opt/app/current/conf/systemd/node_exporter.service"
    dest: /lib/systemd/system/
    directory_mode: yes

- name: Add the prometheus Service Group
  group:
    name: "prometheus"
    state: present

- name: Add the prometheus Service User
  user:
    name: "prometheus"
    groups: "prometheus"
    shell: /sbin/nologin
    create_home: no
    home: /var/lib/prometheus
    append: yes
    comment: "prometheus Service User"
    state: present

- name: Create node_exporter folder
  file:
    path: /opt/prometheus/node_exporter
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Prepare tmp download dir
  file:
    path: "{{ role_path }}/files/tmp"
    state: directory
  delegate_to: localhost

- name: check if package file exists
  stat:
    path: "{{ role_path }}/files/tmp/node_exporter-{{node_exporter_version}}.tgz"
  register: cached_file
  run_once: True
  delegate_to: localhost

- name: Download node_exporter reusable binaries locally
  get_url:
    url: "https://ghproxy.com/https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-arm64.tar.gz"
    dest: "{{ role_path }}/files/tmp/node_exporter-{{node_exporter_version}}.tgz"
  delegate_to: localhost
  run_once: True
  when:
  - cached_file.stat.exists == False

- name: Extract node_exporter binary
  unarchive:
    src: "{{ role_path }}/files/tmp/{{ item }}.tgz"
    dest: "/opt/prometheus/node_exporter/"
    extra_opts: [ --strip-components=1 ]
    owner: root
    group: root
  with_items:
    - "node_exporter-{{node_exporter_version}}"

- name: disable apt auto upgrade
  systemd:
    daemon_reload: yes
    name: node_exporter
    enabled: no
    masked: yes
    state: stopped
  loop:
  - node_exporter
  loop_control:
    loop_var: svc_name

- name: install confd files
  include_tasks: ../../utils/tasks/process-confd-files.yml

