---
- name: set up variables
  set_fact:
    redis_exporter_version: "{{ redis_exporter_version | d('v1.62.0') }}"
    arch: "{{ arch | d(default_arch) }}"
    installPath: "/opt/prometheus/redis_exporter"

- name: Copy files
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/redis_exporter.service"
    dest: "/lib/systemd/system/"
    directory_mode: yes

- name: Add the prometheus Service Group
  group:
    name: "prometheus"
    state: present

- name: Add the prometheus Service User
  user:
    name: "prometheus"
    groups: "prometheus"
    shell: /sbin/nologin
    create_home: no
    home: /var/lib/prometheus
    append: yes
    comment: "prometheus Service User"
    state: present

- name: Create redis_exporter folder
  file:
    path: "{{ installPath }}/{{ redis_exporter_version }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: redis-exporter
      pkg_version: "{{ redis_exporter_version }}"
      pkg_feature: "linux-{{ arch }}"
      pkg_fileType: ".tgz"
      pkg_url: "https://github.com/oliver006/redis_exporter/releases/download/{{redis_exporter_version}}/redis_exporter-{{redis_exporter_version}}.linux-{{ arch }}.tar.gz"

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}/{{ redis_exporter_version }}"
    creates: "{{ installPath }}/{{ redis_exporter_version }}/redis_exporter"
    extra_opts:
    - --strip-components=1

- name: link for current
  file:
    src: "{{ installPath }}/{{ redis_exporter_version }}"
    dest: "{{ installPath }}/current"
    state: link

- name: disable systemd deamon
  systemd:
    daemon_reload: yes
    name: redis_exporter
    enabled: no
    masked: yes
    state: stopped

- name: install confd files
  include_tasks: ../../utils/tasks/process-confd-files.yml

