---
- name: redis standalone
  hosts: redis-standalone
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - redis-standalone
    loop_control:
      loop_var: name

- name: redis cluster
  hosts: redis-cluster
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - redis-cluster
    loop_control:
      loop_var: name
