---

- name: copy rsyslog.conf
  copy: 
    src: "files{{ path }}"
    dest: "{{ path }}"
    owner: root
    group: root
    mode: u=rw,go=r
  loop:
    - /etc/rsyslog.conf
  loop_control:
    loop_var: path
    